export class Sheduler{
  shedulersDefault ={
    "07:00:00":false,
    "08:00:00":false,
    "10:00:00":false,
    "10:05:00":false,
    "12:00:00":false,
    "13:05:00":false,
    "13:15:00":false,
    "14:00:00":false,
    "16:00:00":false,
    "16:05:00":false,
    "18:00:00":false,
    "Lundi":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },
    "Mardi":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },
    "Mercredi":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },
    "Jeudi":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },
    "Vendredi":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },
    "Samedi":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },
    "Dimanche":{
       "07:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
       "08:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "10:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "12:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "13:15:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "14:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "16:05:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
      "18:00:00":{
        "code_cours":"-",
        "code_salle":"",
        "nom_enseignant":""
      },
    },

}
  constructor(){
    this.shedulersDefault=this.shedulersDefault
  }

  renderSheduler(){
    return this.shedulersDefault
  }
}
