import { Injectable } from '@angular/core';
import { Subject, Subscription } from 'rxjs';
import { Sheduler} from 'src/app/models/sheduler.model';
@Injectable({
  providedIn: 'root'
})
export class ArraysService {

  constructor() { }
  filiere = ["","Informatique","Biosciences","Chimie","Geosciences","Mathématique","Physique"]
  code = ["","INFO","BIOS","CHIM","GEOS","MAT","PHYS"]
  niveau = ["","L1","L2","L3","M1","M2"]
  specialiteInfo = ["","Data Science","Génie Logiciel","Réseau","Sécurité"]
  faculte = ["","Sciences","Lettres"]
  salle =["","A135","A250","A350","E204","R101","R102","R103","R104","R105","R110","S006","S008"]
  jour = ["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"]
  heur= ["07:00:00","10:05:00","13:15:00","16:00:00","16:05:00"]
  codeSpecial = ["DS","GL","R","S"]
  specialite = ["Data Science","Génie Logiciel","Réseau","Sécurité"]
  grade = ["Docteur","Professeur"]
  codeGrade = ["Dr","Pr"]
  semestre = ["","SEM1","SEM2"]
  plageHoraire = ["07:00:00 - 09:55:00","08:00:00 - 10:00:00","10:05:00 - 12:55:00","13:05:00 - 15:55:00","13:15:00 - 15:55:00","14:00:00 - 16:00:00","16:00:00 - 18:00:00","16:05:00 - 18:55:00","18:00:00 - 21:55:00"]
  groupe = {
    INFO:"DS_GL_R_S",
    L3:{
      "L3DS":"L3DS_GL_R_S", "L3GL":"L3DS_GL_R_S", "L3R":"L3DS_GL_R_S", "L3S":"L3DS_GL_R_S",
    },
    "M1":{
      "M1DS":"L3DS_GL_R_S", "M1GL":"L3DS_GL_R_S", "M1R":"L3DS_GL_R_S", "M1S":"L3DS_GL_R_S",
    }
  }
chargeSheduler(datas:any){
  let sheduler=new Sheduler().shedulersDefault
  for(let data of datas){
    if(data.jour=='Lundi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Lundi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Lundi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Lundi"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Lundi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Lundi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Lundi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Lundi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Lundi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Lundi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Lundi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Lundi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
      }
    }
    if(data.jour=='Mardi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Mardi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Mardi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Mardi"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Mardi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Mardi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Mardi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Mardi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Mardi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Mardi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Mardi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Mardi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Mercredi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Mercredi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Mercredi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Mercredi"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Mercredi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Mercredi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Mercredi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Mercredi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Mercredi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Mercredi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Mercredi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Mercredi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Jeudi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Jeudi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Jeudi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Jeudi"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Jeudi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Jeudi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Jeudi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Jeudi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Jeudi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Jeudi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Jeudi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Jeudi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Vendredi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Vendredi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Vendredi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Vendredi"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Vendredi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Vendredi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Vendredi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Vendredi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Vendredi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Vendredi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Vendredi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Vendredi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Samedi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Samedi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Samedi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Samedi"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Samedi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Samedi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Samedi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Samedi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Samedi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Samedi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Samedi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Samedi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Dimanche'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Dimanche"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Dimanche"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:00:00"){
        sheduler["Dimanche"]["10:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["10:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["10:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Dimanche"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Dimanche"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Dimanche"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Dimanche"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Dimanche"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Dimanche"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Dimanche"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Dimanche"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
  }
  return sheduler
}

chargeShedulerFilier(datas:any){
  let sheduler=new Sheduler().shedulersDefault
  let donnees=[]
  // for(let data of datas){
  //   if(donnees[data]==undefined){

  //   }
  // }
  for(let data of datas){
    if(data.jour=='Lundi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Lundi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Lundi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Lundi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Lundi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Lundi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Lundi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Lundi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Lundi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Lundi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Lundi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Lundi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Lundi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Lundi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
      }
    }
    if(data.jour=='Mardi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Mardi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Mardi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Mardi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Mardi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Mardi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Mardi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Mardi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Mardi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Mardi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Mardi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mardi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mardi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Mercredi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Mercredi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Mercredi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Mercredi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Mercredi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Mercredi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Mercredi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Mercredi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Mercredi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Mercredi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Mercredi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Mercredi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Mercredi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Jeudi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Jeudi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Jeudi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Jeudi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Jeudi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Jeudi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Jeudi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Jeudi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Jeudi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Jeudi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Jeudi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Jeudi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Jeudi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Vendredi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Vendredi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Vendredi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Vendredi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Vendredi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Vendredi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Vendredi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Vendredi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Vendredi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Vendredi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Vendredi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Vendredi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Vendredi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Samedi'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Samedi"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Samedi"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Samedi"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Samedi"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Samedi"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Samedi"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Samedi"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Samedi"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Samedi"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Samedi"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Samedi"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Samedi"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
    if(data.jour=='Dimanche'){
      if(data.heure_debut=="07:00:00"){
        sheduler["Dimanche"]["07:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["07:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["07:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["07:00:00"]=true;
      }
      if(data.heure_debut=="08:00:00"){
        sheduler["Dimanche"]["08:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["08:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["08:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["08:00:00"]=true;
      }
      if(data.heure_debut=="10:05:00"){
        sheduler["Dimanche"]["10:05:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["10:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["10:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["10:05:00"]=true;
      }
      if(data.heure_debut=="12:00:00"){
        sheduler["Dimanche"]["12:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["12:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["12:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["12:00:00"]=true;
      }
      if(data.heure_debut=="13:05:00"){
        sheduler["Dimanche"]["13:05:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["13:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["13:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:05:00"]=true;
      }
      if(data.heure_debut=="13:15:00"){
        sheduler["Dimanche"]["13:15:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["13:15:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["13:15:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["13:15:00"]=true;
      }
      if(data.heure_debut=="14:00:00"){
        sheduler["Dimanche"]["14:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["14:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["14:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["14:00:00"]=true;
      }
      if(data.heure_debut=="16:00:00"){
        sheduler["Dimanche"]["16:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["16:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["16:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:00:00"]=true;
      }
      if(data.heure_debut=="16:05:00"){
        sheduler["Dimanche"]["16:05:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["16:05:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["16:05:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["16:05:00"]=true;
      }
      if(data.heure_debut=="18:00:00"){
        sheduler["Dimanche"]["18:00:00"]["code_cours"]=data.code_cours;
        sheduler["Dimanche"]["18:00:00"]["code_salle"]="("+data.code_salle+")";
        sheduler["Dimanche"]["18:00:00"]["nom_enseignant"]=data.nom_enseignant;
        sheduler["18:00:00"]=true;
      }
    }
  }
  return sheduler
}

orderByheur(datas:any){
  const heurs = this.heur
  let data=[];
  for(let heur of heurs ){
    for(let dat of datas){
      if( dat.heure_debut==heur){
        data.push(dat)
      }
    }
  }
  return data
}

order(datas:any){
  const jours = this.jour
  let data=[];
  for(let jour of jours ){
    let datatemp=[];
    for(let dat of datas){
      if( dat.jour==jour){
        datatemp.push(dat)
      }
    }
    datatemp = this.orderByheur(datatemp)
    for(let dat of datatemp){
      data.push(dat)
    }
  }
  return data
}

filiereToCode(filiere:string){
  const filiereList=this.filiere;
  const codes = this.code
  let index = filiereList.indexOf(filiere)
  return codes[index]
}
coteToSpecialite(code:string){
  const specialite = this.specialite;
  const codeSpecialite = this.codeSpecial
  let index = codeSpecialite.indexOf(code)
  return specialite[index]
}
specialiteToCode(specialite:string){
  const specialites = this.specialite;
  const codeSpecialite = this.codeSpecial
  let index = specialites.indexOf(specialite)
  return codeSpecialite[index]
}

chargeGroupeSet(filiere:string,niveau:string){
    if(filiere=="INFO"){
      return niveau+this.groupe.INFO
    }
    return ""
}

}
